import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const base = process.argv[2] || 'http://127.0.0.1:4839/templates/';
const browser = await chromium.launch();
try {
 const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
 const errors: string[] = [], api: string[] = [];
 page.on('pageerror', e => errors.push(e.message));
 page.on('request', r => { if (/\/api\//.test(r.url())) api.push(r.url()); });
 await page.goto(base + '#connection');
 const open = async () => page.getByRole('button',{name:'Connect Codex',exact:true}).click();
 await open();
 await page.getByRole('button',{name:'Sign in with ChatGPT',exact:true}).click();
 await expect(page.getByRole('link',{name:'Continue sign-in ↗',exact:true})).toBeVisible();
 await expect(page.getByRole('dialog')).not.toContainText(/mock|simulat/i);
 await page.getByRole('button',{name:'Cancel sign-in',exact:true}).click();
 await expect(page.getByRole('button',{name:'Test connection',exact:true})).toBeDisabled();
 await open();
 await page.getByRole('button',{name:'Use device code',exact:true}).click();
 await page.getByRole('link',{name:'Continue sign-in ↗',exact:true}).click();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await page.getByRole('button',{name:'Cancel test',exact:true}).click();
 await expect(page.getByLabel('Connection test result')).toBeEmpty();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await expect(page.getByLabel('Connection test result')).toContainText('Hello! Your connection is ready.');
 await page.getByRole('button',{name:'● Codex connected',exact:true}).click();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'Confirm sign out',exact:true}).click();
 await page.getByRole('button',{name:'Connection failed Alternative path',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('Connection failed');
 await open();
 await page.getByRole('button',{name:'Retry connection',exact:true}).click();
 await page.getByRole('link',{name:'Continue sign-in ↗',exact:true}).click();
 await page.reload();
 await expect(page.getByRole('button',{name:'Test connection',exact:true})).toBeDisabled();
 const banner = await page.locator('.hosted-notice').boundingBox(), tabs = await page.locator('.template-toolbar').boundingBox();
 expect(banner!.y - (tabs!.y + tabs!.height)).toBeGreaterThanOrEqual(20);
 await mkdir('test-results/mock-flows',{recursive:true});
 await open();
 await page.getByRole('button',{name:'Sign in with ChatGPT',exact:true}).click();
 await page.screenshot({path:'test-results/mock-flows/connection-production.png',fullPage:true});
 await page.getByRole('button',{name:'Cancel sign-in',exact:true}).click();
 for (const kind of ['character','style']) {
  await page.goto(base+'#'+kind);
  const send = async (text:string) => { await page.getByRole('textbox',{name:'Message',exact:true}).fill(text); await page.getByRole('button',{name:'Send message',exact:true}).click(); };
  await send('Can we discuss an idea first?');
  await expect(page.getByRole('log')).toContainText('Can we discuss an idea first?');
  await expect(page.getByRole('button',{name:'Stop',exact:true})).not.toBeVisible();
  await send('Update the brief');
  await page.getByText('Update design brief',{exact:true}).click();
  await expect(page.getByRole('log')).toContainText('updated');
  await send('Generate a preview');
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await expect(page.getByText('Stopped',{exact:true})).toBeVisible();
  await send('Generate again');
  await expect(page.getByRole('button',{name:`Use this ${kind}`,exact:false})).toBeEnabled();
  await send('Make it softer');
  await page.getByRole('button',{name:'Select version 1',exact:true}).click();
  await expect(page.getByRole('button',{name:'Select version 1',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('.mock-chat-step')).not.toContainText(/mock|simulat/i);
  await page.screenshot({path:`test-results/mock-flows/${kind}-production.png`,fullPage:true});
  await page.getByRole('button',{name:`Use this ${kind}`,exact:false}).click();
  await expect(page.getByRole('heading',{name:`Your ${kind} is ready.`,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Generation failed Alternative path',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Generation failed');
  await page.getByRole('button',{name:'Reset demo',exact:true}).click();
  await expect(page.getByRole('log')).not.toContainText('Can we discuss');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});
 }
 await page.getByRole('button',{name:'Play E2E',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Your style is ready.',exact:true})).toBeVisible({timeout:25000});
 expect(errors).toEqual([]); expect(api).toEqual([]);
 console.log('Production-component mock E2E passed: auth dialog, cancellation, testing, sign-out, retry, reset, chat streaming/tools/versions/acceptance, autoplay, mobile, no API calls.');
} finally { await browser.close(); }
