import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const base = process.argv[2] || 'http://127.0.0.1:4839/templates/';
const browser = await chromium.launch();
try {
 const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
 const errors: string[] = [], api: string[] = [];
 page.on('pageerror', e => errors.push(e.message));
 page.on('request', r => { if (/\/api\//.test(r.url())) api.push(r.url()); });
 await page.goto(base + '#connection');
 await page.getByRole('button', { name: 'Sign in with Codex →', exact: true }).click();
 await page.getByRole('button', { name: 'Cancel sign-in', exact: true }).click();
 await expect(page.getByRole('button', { name: 'Test connection', exact: true })).toBeDisabled();
 await page.getByRole('button', { name: 'Sign in with Codex →', exact: true }).click();
 await page.getByRole('button', { name: 'Approve mock sign-in', exact: true }).click();
 await page.getByRole('button', { name: 'Test connection', exact: true }).click();
 await expect(page.getByText('Hello! Your connection is ready. (Mock response)', { exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Sign out', exact: true }).click();
 await page.getByRole('button', { name: 'Connection failed Alternative path', exact: true }).click();
 await expect(page.getByRole('alert')).toContainText('simulated connection failed');
 await page.getByRole('button', { name: 'Retry connection', exact: true }).click();
 await page.getByRole('button', { name: 'Approve mock sign-in', exact: true }).click();
 await page.reload();
 await expect(page.getByRole('button', { name: 'Test connection', exact: true })).toBeDisabled();
 await page.getByRole('button', { name: 'Play E2E', exact: true }).click();
 await expect(page.getByRole('button', { name: 'Approve mock sign-in', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Pause walkthrough', exact: true }).click();
 await page.waitForTimeout(2500);
 await expect(page.getByRole('button', { name: 'Approve mock sign-in', exact: true })).toBeVisible();
 await mkdir('test-results/mock-flows', { recursive: true });
 await page.screenshot({path:'test-results/mock-flows/connection.png',fullPage:true});
 for (const kind of ['character','style']) {
  await page.goto(base + '#' + kind);
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('Can we discuss an idea first?');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByRole('log')).toContainText('Can we discuss an idea first?');
  await expect(page.getByRole('button', { name: 'Update the brief', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Update the brief', exact: true }).click();
  await page.getByText('Update design brief', { exact: true }).click();
  await expect(page.getByRole('log')).toContainText('updated');
  await page.getByRole('button', { name: 'Generate a preview', exact: true }).click();
  await page.getByRole('button', { name: 'Stop', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Generation cancelled', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Retry generation', exact: true }).click();
  await expect(page.getByRole('img', { name: `Mock ${kind} sample, version 1`, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Refine this result', exact: true }).click();
  await expect(page.getByRole('img', { name: `Mock ${kind} sample, version 2`, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Version 1', exact: true }).click();
  await page.getByRole('button', { name: `Use this ${kind} →`, exact: true }).click();
  await expect(page.getByText('Version 1 accepted. This step is complete.', { exact: true })).toBeVisible();
  await page.screenshot({path:`test-results/mock-flows/${kind}.png`,fullPage:true});
  await page.getByRole('button', { name: 'Generation failed Alternative path', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Generation failed', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  await expect(page.getByRole('log')).not.toContainText('Can we discuss');
  await page.setViewportSize({ width:390, height:844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width:1440, height:1000 });
 }
 await page.getByRole('button', { name: 'Play E2E', exact: true }).click();
 await expect(page.getByText('Version 2 accepted. This step is complete.', { exact: true })).toBeVisible({ timeout:25000 });
 await expect(page.getByRole('button', { name:'Play E2E',exact:true })).toBeVisible();
 expect(errors).toEqual([]); expect(api).toEqual([]);
 console.log('Mock E2E passed: sign-in/cancel/retry/sign-out/reset, walkthrough pause, streaming/tools/generation/stop/retry/versions/accept, both chat variants, mobile, zero API requests.');
} finally { await browser.close(); }
